---
# Só mude aqui!!!!
author: "Hugo Filho"
title: "Relatório 01"
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: now
date-format: "DD/MM/YYYY, HH:mm"
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---


## 📌 Introdução

A prática consiste na aplicação do conteúdo visto no curso **R Básico**.



## 🎯 Objetivos

### Objetivo geral

Realizar um introdução ao R, fundamentado nas 26 aulas do curso R Básico 2024.

### Objetivos específicos

Resolver um sistema linear através do Método De Gauss, implementando o conteúdo visto durante o curso.

  
---

## 📚  Fundamentação Teórica

  O método da Eliminação de Gauss consiste em anular o triângulo inferior de uma matriz A através de operações elementares entre as linhas.


---

## ⚙️ Metodologia

A partir de uma matriz A:
```r
A<-matrix(c(2,3,-1,4,4,-3,2,-3,1),3,3, byrow=TRUE)
A
```

---

## 🔍 Resultados e Discussão



Procure não apenas descrever, mas **interpretar os dados**.

### 💬 Exemplo de como citar uma referência bibliográfica

Depois de inserido as informaçõe no arquivo **referencias.bib**, use:

- Segundo @Rbasico2022
- Tudo é um objeto em R [@Rbasico2022]

### 📊  Análise de Dados



## 🧠 Considerações finais



## Aprenda Quarto

Acesse [Quarto](https://quarto.org/).

## 📖 Referências