---
# Só mude aqui!!!!
author: "Hugo Araújo Souza Filho"
title: "Relatório de Aula Prática 06"
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: today
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---

## Introdução

Esta prática teve como objetivo o desenvolvimento e a publicação de uma página web pessoal no GitHub, estruturada para funcionar como um portfólio acadêmico. Para isso, utilizou-se o pacote `blogdown` no ambiente R, perfeitamente integrado ao gerador de sites estáticos Hugo.

## Seleção do Tema

A primeira etapa consistiu na escolha de um tema no repositório oficial do Hugo (https://themes.gohugo.io/). O critério principal foi encontrar um layout que comportasse o armazenamento organizado de projetos pessoais e materiais públicos de estudo. O tema selecionado foi o [Blowfish](https://themes.gohugo.io/themes/blowfish/), desenvolvido por Nuno Coração, escolhido por seu design limpo, suporte nativo a modo escuro e excelente organização hierárquica.

## Inicialização do Site

O projeto foi iniciado no RStudio através da criação de um novo *Blogdown Site*. Durante essa configuração, o repositório GitHub do tema Blowfish foi fornecido como parâmetro. A estrutura base de diretórios foi gerada e o site instanciado localmente (em *localhost*) utilizando a função `blogdown::serve_site()`, permitindo a visualização em tempo real das alterações em fase de desenvolvimento.

## Configuração do Ambiente

Seguindo as boas práticas recomendadas, todo o ambiente foi configurado antes da inserção de conteúdos. Inicialmente, os arquivos de configuração foram padronizados de `.toml` para `.yaml`, garantindo maior integração. Em seguida, os metadados pessoais foram ajustados e a taxonomia do site foi estruturada em duas seções principais: "Estudos" e "Projetos". O objetivo visual foi estabelecer um tema escuro com uma página inicial minimalista, categorizando claramente o escopo de cada material.

## Estruturação de Conteúdo

Com a infraestrutura pronta, a seção "Projetos" foi alimentada com o conteúdo da página da equipe [E-CAP](ryuug0.github.io/ecap), da qual faço parte. Já na seção "Estudos", foi criada uma categoria dedicada à atual disciplina de Linguagem R em Ciência de Dados, onde os relatórios das aulas práticas foram hospedados. Durante este processo, ocorreu uma falha técnica no versionamento que resultou na perda temporária dos relatórios no repositório original do curso. A necessidade de reconstrução e readequação dos arquivos justifica a submissão tardia do presente relatório.

## Implantação e Conclusão

Para finalizar e automatizar o fluxo de trabalho, utilizei a função `git()`, proveniente do meu pacote autoral `graf` (desenvolvido na prática anterior). Essa função foi executada para renderizar o documento, compilar (via *knit*), realizar o *commit* e efetuar o *push* dos arquivos para o repositório remoto de forma eficiente. Após esse envio, ativei o *deployment* no GitHub Pages, consolidando [minha página pessoal](ryuug0.github.io). Com isso, o ambiente encontra-se ativado, totalmente funcional e pronto para hospedar de maneira contínua meus projetos e materiais de estudo.